package main

// generated from FridaContainer utils/android/jni/jni_env.json
type jniFunc struct {
	Name string
	Args []string
	Ret  string
}

var jniSchema = []jniFunc{
	{Name: "reserved0", Args: []string{}, Ret: "void"},
	{Name: "reserved1", Args: []string{}, Ret: "void"},
	{Name: "reserved2", Args: []string{}, Ret: "void"},
	{Name: "reserved3", Args: []string{}, Ret: "void"},
	{Name: "GetVersion", Args: []string{"JNIEnv*"}, Ret: "jint"},
	{Name: "DefineClass", Args: []string{"JNIEnv*", "char*", "jobject", "jbyte*", "jsize"}, Ret: "jclass"},
	{Name: "FindClass", Args: []string{"JNIEnv*", "char*"}, Ret: "jclass"},
	{Name: "FromReflectedMethod", Args: []string{"JNIEnv*", "jobject"}, Ret: "jmethodID"},
	{Name: "FromReflectedField", Args: []string{"JNIEnv*", "jobject"}, Ret: "jfieldID"},
	{Name: "ToReflectedMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jboolean"}, Ret: "jobject"},
	{Name: "GetSuperclass", Args: []string{"JNIEnv*", "jclass"}, Ret: "jclass"},
	{Name: "IsAssignableFrom", Args: []string{"JNIEnv*", "jclass", "jclass"}, Ret: "jboolean"},
	{Name: "ToReflectedField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jboolean"}, Ret: "jobject"},
	{Name: "Throw", Args: []string{"JNIEnv*", "jthrowable"}, Ret: "jint"},
	{Name: "ThrowNew", Args: []string{"JNIEnv*", "jclass", "char*"}, Ret: "jint"},
	{Name: "ExceptionOccurred", Args: []string{"JNIEnv*"}, Ret: "jthrowable"},
	{Name: "ExceptionDescribe", Args: []string{"JNIEnv*"}, Ret: "void"},
	{Name: "ExceptionClear", Args: []string{"JNIEnv*"}, Ret: "void"},
	{Name: "FatalError", Args: []string{"JNIEnv*", "char*"}, Ret: "void"},
	{Name: "PushLocalFrame", Args: []string{"JNIEnv*", "jint"}, Ret: "jint"},
	{Name: "PopLocalFrame", Args: []string{"JNIEnv*", "jobject"}, Ret: "jobject"},
	{Name: "NewGlobalRef", Args: []string{"JNIEnv*", "jobject"}, Ret: "jobject"},
	{Name: "DeleteGlobalRef", Args: []string{"JNIEnv*", "jobject"}, Ret: "void"},
	{Name: "DeleteLocalRef", Args: []string{"JNIEnv*", "jobject"}, Ret: "void"},
	{Name: "IsSameObject", Args: []string{"JNIEnv*", "jobject", "jobject"}, Ret: "jboolean"},
	{Name: "NewLocalRef", Args: []string{"JNIEnv*", "jobject"}, Ret: "jobject"},
	{Name: "EnsureLocalCapacity", Args: []string{"JNIEnv*", "jint"}, Ret: "jint"},
	{Name: "AllocObject", Args: []string{"JNIEnv*", "jclass"}, Ret: "jobject"},
	{Name: "NewObject", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jobject"},
	{Name: "NewObjectV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jobject"},
	{Name: "NewObjectA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jobject"},
	{Name: "GetObjectClass", Args: []string{"JNIEnv*", "jobject"}, Ret: "jclass"},
	{Name: "IsInstanceOf", Args: []string{"JNIEnv*", "jobject", "jclass"}, Ret: "jboolean"},
	{Name: "GetMethodID", Args: []string{"JNIEnv*", "jclass", "char*", "char*"}, Ret: "jmethodID"},
	{Name: "CallObjectMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jobject"},
	{Name: "CallObjectMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jobject"},
	{Name: "CallObjectMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jobject"},
	{Name: "CallBooleanMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jboolean"},
	{Name: "CallBooleanMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jboolean"},
	{Name: "CallBooleanMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jboolean"},
	{Name: "CallByteMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jbyte"},
	{Name: "CallByteMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jbyte"},
	{Name: "CallByteMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jbyte"},
	{Name: "CallCharMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jchar"},
	{Name: "CallCharMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jchar"},
	{Name: "CallCharMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jchar"},
	{Name: "CallShortMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jshort"},
	{Name: "CallShortMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jshort"},
	{Name: "CallShortMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jshort"},
	{Name: "CallIntMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jint"},
	{Name: "CallIntMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jint"},
	{Name: "CallIntMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jint"},
	{Name: "CallLongMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jlong"},
	{Name: "CallLongMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jlong"},
	{Name: "CallLongMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jlong"},
	{Name: "CallFloatMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jfloat"},
	{Name: "CallFloatMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jfloat"},
	{Name: "CallFloatMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jfloat"},
	{Name: "CallDoubleMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "jdouble"},
	{Name: "CallDoubleMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "jdouble"},
	{Name: "CallDoubleMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "jdouble"},
	{Name: "CallVoidMethod", Args: []string{"JNIEnv*", "jobject", "jmethodID", "..."}, Ret: "void"},
	{Name: "CallVoidMethodV", Args: []string{"JNIEnv*", "jobject", "jmethodID", "va_list"}, Ret: "void"},
	{Name: "CallVoidMethodA", Args: []string{"JNIEnv*", "jobject", "jmethodID", "jvalue*"}, Ret: "void"},
	{Name: "CallNonvirtualObjectMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jobject"},
	{Name: "CallNonvirtualObjectMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jobject"},
	{Name: "CallNonvirtualObjectMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jobject"},
	{Name: "CallNonvirtualBooleanMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jboolean"},
	{Name: "CallNonvirtualBooleanMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jboolean"},
	{Name: "CallNonvirtualBooleanMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jboolean"},
	{Name: "CallNonvirtualByteMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jbyte"},
	{Name: "CallNonvirtualByteMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jbyte"},
	{Name: "CallNonvirtualByteMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jbyte"},
	{Name: "CallNonvirtualCharMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jchar"},
	{Name: "CallNonvirtualCharMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jchar"},
	{Name: "CallNonvirtualCharMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jchar"},
	{Name: "CallNonvirtualShortMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jshort"},
	{Name: "CallNonvirtualShortMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jshort"},
	{Name: "CallNonvirtualShortMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jshort"},
	{Name: "CallNonvirtualIntMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jint"},
	{Name: "CallNonvirtualIntMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jint"},
	{Name: "CallNonvirtualIntMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jint"},
	{Name: "CallNonvirtualLongMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jlong"},
	{Name: "CallNonvirtualLongMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jlong"},
	{Name: "CallNonvirtualLongMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jlong"},
	{Name: "CallNonvirtualFloatMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jfloat"},
	{Name: "CallNonvirtualFloatMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jfloat"},
	{Name: "CallNonvirtualFloatMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jfloat"},
	{Name: "CallNonvirtualDoubleMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "jdouble"},
	{Name: "CallNonvirtualDoubleMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "jdouble"},
	{Name: "CallNonvirtualDoubleMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "jdouble"},
	{Name: "CallNonvirtualVoidMethod", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "..."}, Ret: "void"},
	{Name: "CallNonvirtualVoidMethodV", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "va_list"}, Ret: "void"},
	{Name: "CallNonvirtualVoidMethodA", Args: []string{"JNIEnv*", "jobject", "jclass", "jmethodID", "jvalue*"}, Ret: "void"},
	{Name: "GetFieldID", Args: []string{"JNIEnv*", "jclass", "char*", "char*"}, Ret: "jfieldID"},
	{Name: "GetObjectField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jobject"},
	{Name: "GetBooleanField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jboolean"},
	{Name: "GetByteField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jbyte"},
	{Name: "GetCharField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jchar"},
	{Name: "GetShortField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jshort"},
	{Name: "GetIntField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jint"},
	{Name: "GetLongField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jlong"},
	{Name: "GetFloatField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jfloat"},
	{Name: "GetDoubleField", Args: []string{"JNIEnv*", "jobject", "jfieldID"}, Ret: "jdouble"},
	{Name: "SetObjectField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jobject"}, Ret: "void"},
	{Name: "SetBooleanField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jboolean"}, Ret: "void"},
	{Name: "SetByteField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jbyte"}, Ret: "void"},
	{Name: "SetCharField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jchar"}, Ret: "void"},
	{Name: "SetShortField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jshort"}, Ret: "void"},
	{Name: "SetIntField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jint"}, Ret: "void"},
	{Name: "SetLongField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jlong"}, Ret: "void"},
	{Name: "SetFloatField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jfloat"}, Ret: "void"},
	{Name: "SetDoubleField", Args: []string{"JNIEnv*", "jobject", "jfieldID", "jdouble"}, Ret: "void"},
	{Name: "GetStaticMethodID", Args: []string{"JNIEnv*", "jclass", "char*", "char*"}, Ret: "jmethodID"},
	{Name: "CallStaticObjectMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jobject"},
	{Name: "CallStaticObjectMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jobject"},
	{Name: "CallStaticObjectMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jobject"},
	{Name: "CallStaticBooleanMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jboolean"},
	{Name: "CallStaticBooleanMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jboolean"},
	{Name: "CallStaticBooleanMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jboolean"},
	{Name: "CallStaticByteMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jbyte"},
	{Name: "CallStaticByteMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jbyte"},
	{Name: "CallStaticByteMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jbyte"},
	{Name: "CallStaticCharMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jchar"},
	{Name: "CallStaticCharMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jchar"},
	{Name: "CallStaticCharMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jchar"},
	{Name: "CallStaticShortMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jshort"},
	{Name: "CallStaticShortMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jshort"},
	{Name: "CallStaticShortMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jshort"},
	{Name: "CallStaticIntMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jint"},
	{Name: "CallStaticIntMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jint"},
	{Name: "CallStaticIntMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jint"},
	{Name: "CallStaticLongMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jlong"},
	{Name: "CallStaticLongMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jlong"},
	{Name: "CallStaticLongMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jlong"},
	{Name: "CallStaticFloatMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jfloat"},
	{Name: "CallStaticFloatMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jfloat"},
	{Name: "CallStaticFloatMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jfloat"},
	{Name: "CallStaticDoubleMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "jdouble"},
	{Name: "CallStaticDoubleMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "jdouble"},
	{Name: "CallStaticDoubleMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "jdouble"},
	{Name: "CallStaticVoidMethod", Args: []string{"JNIEnv*", "jclass", "jmethodID", "..."}, Ret: "void"},
	{Name: "CallStaticVoidMethodV", Args: []string{"JNIEnv*", "jclass", "jmethodID", "va_list"}, Ret: "void"},
	{Name: "CallStaticVoidMethodA", Args: []string{"JNIEnv*", "jclass", "jmethodID", "jvalue*"}, Ret: "void"},
	{Name: "GetStaticFieldID", Args: []string{"JNIEnv*", "jclass", "char*", "char*"}, Ret: "jfieldID"},
	{Name: "GetStaticObjectField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jobject"},
	{Name: "GetStaticBooleanField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jboolean"},
	{Name: "GetStaticByteField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jbyte"},
	{Name: "GetStaticCharField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jchar"},
	{Name: "GetStaticShortField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jshort"},
	{Name: "GetStaticIntField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jint"},
	{Name: "GetStaticLongField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jlong"},
	{Name: "GetStaticFloatField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jfloat"},
	{Name: "GetStaticDoubleField", Args: []string{"JNIEnv*", "jclass", "jfieldID"}, Ret: "jdouble"},
	{Name: "SetStaticObjectField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jobject"}, Ret: "void"},
	{Name: "SetStaticBooleanField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jboolean"}, Ret: "void"},
	{Name: "SetStaticByteField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jbyte"}, Ret: "void"},
	{Name: "SetStaticCharField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jchar"}, Ret: "void"},
	{Name: "SetStaticShortField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jshort"}, Ret: "void"},
	{Name: "SetStaticIntField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jint"}, Ret: "void"},
	{Name: "SetStaticLongField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jlong"}, Ret: "void"},
	{Name: "SetStaticFloatField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jfloat"}, Ret: "void"},
	{Name: "SetStaticDoubleField", Args: []string{"JNIEnv*", "jclass", "jfieldID", "jdouble"}, Ret: "void"},
	{Name: "NewString", Args: []string{"JNIEnv*", "jchar*", "jsize"}, Ret: "jstring"},
	{Name: "GetStringLength", Args: []string{"JNIEnv*", "jstring"}, Ret: "jsize"},
	{Name: "GetStringChars", Args: []string{"JNIEnv*", "jstring", "jboolean*"}, Ret: "jchar*"},
	{Name: "ReleaseStringChars", Args: []string{"JNIEnv*", "jstring", "jchar*"}, Ret: "void"},
	{Name: "NewStringUTF", Args: []string{"JNIEnv*", "char*"}, Ret: "jstring"},
	{Name: "GetStringUTFLength", Args: []string{"JNIEnv*", "jstring"}, Ret: "jsize"},
	{Name: "GetStringUTFChars", Args: []string{"JNIEnv*", "jstring", "jboolean*"}, Ret: "char*"},
	{Name: "ReleaseStringUTFChars", Args: []string{"JNIEnv*", "jstring", "char*"}, Ret: "void"},
	{Name: "GetArrayLength", Args: []string{"JNIEnv*", "jarray"}, Ret: "jsize"},
	{Name: "NewObjectArray", Args: []string{"JNIEnv*", "jsize", "jclass", "jobject"}, Ret: "jobjectArray"},
	{Name: "GetObjectArrayElement", Args: []string{"JNIEnv*", "jobjectArray", "jsize"}, Ret: "jobject"},
	{Name: "SetObjectArrayElement", Args: []string{"JNIEnv*", "jobjectArray", "jsize", "jobject"}, Ret: "void"},
	{Name: "NewBooleanArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jbooleanArray"},
	{Name: "NewByteArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jbyteArray"},
	{Name: "NewCharArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jcharArray"},
	{Name: "NewShortArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jshortArray"},
	{Name: "NewIntArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jintArray"},
	{Name: "NewLongArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jlongArray"},
	{Name: "NewFloatArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jfloatArray"},
	{Name: "NewDoubleArray", Args: []string{"JNIEnv*", "jsize"}, Ret: "jdoubleArray"},
	{Name: "GetBooleanArrayElements", Args: []string{"JNIEnv*", "jbooleanArray", "jboolean*"}, Ret: "jboolean*"},
	{Name: "GetByteArrayElements", Args: []string{"JNIEnv*", "jbyteArray", "jboolean*"}, Ret: "jbyte*"},
	{Name: "GetCharArrayElements", Args: []string{"JNIEnv*", "jcharArray", "jboolean*"}, Ret: "jchar*"},
	{Name: "GetShortArrayElements", Args: []string{"JNIEnv*", "jshortArray", "jboolean*"}, Ret: "jshort*"},
	{Name: "GetIntArrayElements", Args: []string{"JNIEnv*", "jintArray", "jboolean*"}, Ret: "jint*"},
	{Name: "GetLongArrayElements", Args: []string{"JNIEnv*", "jlongArray", "jboolean*"}, Ret: "jlong*"},
	{Name: "GetFloatArrayElements", Args: []string{"JNIEnv*", "jfloatArray", "jboolean*"}, Ret: "jfloat*"},
	{Name: "GetDoubleArrayElements", Args: []string{"JNIEnv*", "jdoubleArray", "jboolean*"}, Ret: "jdouble*"},
	{Name: "ReleaseBooleanArrayElements", Args: []string{"JNIEnv*", "jbooleanArray", "jboolean*", "jint"}, Ret: "void"},
	{Name: "ReleaseByteArrayElements", Args: []string{"JNIEnv*", "jbyteArray", "jbyte*", "jint"}, Ret: "void"},
	{Name: "ReleaseCharArrayElements", Args: []string{"JNIEnv*", "jcharArray", "jchar*", "jint"}, Ret: "void"},
	{Name: "ReleaseShortArrayElements", Args: []string{"JNIEnv*", "jshortArray", "jshort*", "jint"}, Ret: "void"},
	{Name: "ReleaseIntArrayElements", Args: []string{"JNIEnv*", "jintArray", "jint*", "jint"}, Ret: "void"},
	{Name: "ReleaseLongArrayElements", Args: []string{"JNIEnv*", "jlongArray", "jlong*", "jint"}, Ret: "void"},
	{Name: "ReleaseFloatArrayElements", Args: []string{"JNIEnv*", "jfloatArray", "jfloat*", "jint"}, Ret: "void"},
	{Name: "ReleaseDoubleArrayElements", Args: []string{"JNIEnv*", "jdoubleArray", "jdouble*", "jint"}, Ret: "void"},
	{Name: "GetBooleanArrayRegion", Args: []string{"JNIEnv*", "jbooleanArray", "jsize", "jsize", "jboolean*"}, Ret: "void"},
	{Name: "GetByteArrayRegion", Args: []string{"JNIEnv*", "jbyteArray", "jsize", "jsize", "jbyte*"}, Ret: "void"},
	{Name: "GetCharArrayRegion", Args: []string{"JNIEnv*", "jcharArray", "jsize", "jsize", "jchar*"}, Ret: "void"},
	{Name: "GetShortArrayRegion", Args: []string{"JNIEnv*", "jshortArray", "jsize", "jsize", "jshort*"}, Ret: "void"},
	{Name: "GetIntArrayRegion", Args: []string{"JNIEnv*", "jintArray", "jsize", "jsize", "jint*"}, Ret: "void"},
	{Name: "GetLongArrayRegion", Args: []string{"JNIEnv*", "jlongArray", "jsize", "jsize", "jlong*"}, Ret: "void"},
	{Name: "GetFloatArrayRegion", Args: []string{"JNIEnv*", "jfloatArray", "jsize", "jsize", "jfloat*"}, Ret: "void"},
	{Name: "GetDoubleArrayRegion", Args: []string{"JNIEnv*", "jdoubleArray", "jsize", "jsize", "jdouble*"}, Ret: "void"},
	{Name: "SetBooleanArrayRegion", Args: []string{"JNIEnv*", "jbooleanArray", "jsize", "jsize", "jboolean*"}, Ret: "void"},
	{Name: "SetByteArrayRegion", Args: []string{"JNIEnv*", "jbyteArray", "jsize", "jsize", "jbyte*"}, Ret: "void"},
	{Name: "SetCharArrayRegion", Args: []string{"JNIEnv*", "jcharArray", "jsize", "jsize", "jchar*"}, Ret: "void"},
	{Name: "SetShortArrayRegion", Args: []string{"JNIEnv*", "jshortArray", "jsize", "jsize", "jshort*"}, Ret: "void"},
	{Name: "SetIntArrayRegion", Args: []string{"JNIEnv*", "jintArray", "jsize", "jsize", "jint*"}, Ret: "void"},
	{Name: "SetLongArrayRegion", Args: []string{"JNIEnv*", "jlongArray", "jsize", "jsize", "jlong*"}, Ret: "void"},
	{Name: "SetFloatArrayRegion", Args: []string{"JNIEnv*", "jfloatArray", "jsize", "jsize", "jfloat*"}, Ret: "void"},
	{Name: "SetDoubleArrayRegion", Args: []string{"JNIEnv*", "jdoubleArray", "jsize", "jsize", "jdouble*"}, Ret: "void"},
	{Name: "RegisterNatives", Args: []string{"JNIEnv*", "jclass", "JNINativeMethod*", "jint"}, Ret: "jint"},
	{Name: "UnregisterNatives", Args: []string{"JNIEnv*", "jclass"}, Ret: "jint"},
	{Name: "MonitorEnter", Args: []string{"JNIEnv*", "jobject"}, Ret: "jint"},
	{Name: "MonitorExit", Args: []string{"JNIEnv*", "jobject"}, Ret: "jint"},
	{Name: "GetJavaVM", Args: []string{"JNIEnv*", "JavaVM**"}, Ret: "jint"},
	{Name: "GetStringRegion", Args: []string{"JNIEnv*", "jstring", "jsize", "jsize", "jchar*"}, Ret: "void"},
	{Name: "GetStringUTFRegion", Args: []string{"JNIEnv*", "jstring", "jsize", "jsize", "char*"}, Ret: "void"},
	{Name: "GetPrimitiveArrayCritical", Args: []string{"JNIEnv*", "jarray", "jboolean*"}, Ret: "void"},
	{Name: "ReleasePrimitiveArrayCritical", Args: []string{"JNIEnv*", "jarray", "void*", "jint"}, Ret: "void"},
	{Name: "GetStringCritical", Args: []string{"JNIEnv*", "jstring", "jboolean*"}, Ret: "jchar"},
	{Name: "ReleaseStringCritical", Args: []string{"JNIEnv*", "jstring", "jchar*"}, Ret: "void"},
	{Name: "NewWeakGlobalRef", Args: []string{"JNIEnv*", "jobject"}, Ret: "jweak"},
	{Name: "DeleteWeakGlobalRef", Args: []string{"JNIEnv*", "jweak"}, Ret: "void"},
	{Name: "ExceptionCheck", Args: []string{"JNIEnv*"}, Ret: "jboolean"},
	{Name: "NewDirectByteBuffer", Args: []string{"JNIEnv*", "void*", "jlong"}, Ret: "jobject"},
	{Name: "GetDirectBufferAddress", Args: []string{"JNIEnv*", "jobject"}, Ret: "void"},
	{Name: "GetDirectBufferCapacity", Args: []string{"JNIEnv*", "jobject"}, Ret: "jlong"},
	{Name: "GetObjectRefType", Args: []string{"JNIEnv*", "jobject"}, Ret: "jobjectRefType"},
}

